module.exports = {
  CONNECTION_RESPONSE_MESSAGE: 0x20,
  PUBLISH_MESSAGE: 0x30,
  PUBACK_MESSAGE: 0x40,
  WATCHDOG_MESSAGE: 0xC0,

  CRASH_EVENT_TYPE: 0x43,
  PHYD_EVENT_TYPE: 0x50,
  PHYD_CALIBRATION_EVENT_TYPE: 0x56,
  
  IOTP: {
	  PHYD_MESSAGE: 'PHYD',
	  CRASH_MESSAGE: 'CRASH',
	  CALIB_MESSAGE: 'CALIB',
	  STATUS_MESSAGE: 'STATUS',
	  JSON_FORMAT: 'json'
  }
};
